---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directories: 
      - "/"
      - "/base"
      - "/jt400"
      - "/manager"
      - "/nosql"
      - "/sql"
    schedule:
      interval: "weekly"
    # group dependencies that will be updated together in one pull request
    groups:
      test-db-drivers:
        patterns:
          - "*hsqldb*"
          - "*mysql*"
          - "*h2database*"
      junit-deps:
        patterns:
          - "*junit*"
      mvn-plugin-deps:
        patterns:
          - "*plugin*"