name: Deploy to Maven Central

on:
  push:
    branches: [master]  # Restrict deployment to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Java and Maven credentials
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      # Deploy with Maven
      - name: Deploy with Maven
        run: mvn -B clean deploy -DautoDropAfterRelease=true -DskipTests -Pci-cd
