name: Deploy to maven central
on:
  push:
    branches: #[master, develop]
      - feat/add-reusable-workflow
jobs:
  workflow-trigger:
    #needs: build
    uses: smeup/devops/.github/workflows/workflow-trigger.yaml@refactor/working-directory
    with:
      repo-name: kokos
      action-file-name: develop-release.yml
      branch-name: develop
    secrets:
      GITHUB_PAT: ${{ secrets.ROBBY_SMEUP_PAT }}
